name: release

on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  metadata:
    runs-on: ubuntu-latest
    steps:
      - name: Update project metadata and release pull request
        uses: googleapis/release-please-action@v4
        with:
          release-type: node
